/**
 * Typed access to the nibabel conformance manifest and shared tolerances.
 *
 * The manifest and fixtures are generated by `npm run conformance:generate`
 * (scripts/conformance/). Tests only read committed files; no Python needed.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { expect, it } from 'vitest';
import type { NamedAxis } from '../../src/geometry/Axis';

export const FIXTURE_ROOT = join(__dirname, 'fixtures');

export type Matrix4 = number[][];

export interface ConformanceCase {
  id: string;
  description: string;
  file: string;
  sha256: string;
  format: 'nifti1' | 'nifti2';
  compressed: boolean;
  endian: 'little' | 'big';
  tags: string[];
  shape: number[];
  header: {
    dim: number[];
    pixdim: number[];
    datatype: number;
    dtype: string;
    bitpix: number;
    vox_offset: number;
    /** Raw stored field; null when NaN/inf. */
    scl_slope: number | null;
    scl_inter: number | null;
    qform_code: number;
    sform_code: number;
    zooms: number[];
  };
  /** Scaling nibabel actually applies (1/0 when the header disables scaling). */
  scaling: { slope: number; inter: number };
  affine: Matrix4;
  qform: Matrix4 | null;
  sform: Matrix4 | null;
  voxel_sizes: number[];
  axcodes: string[];
  canonical: { shape: number[]; affine: Matrix4; axcodes: string[] };
  samples: { ijk: number[]; xyz: number[] }[];
  volumes: { scaled: number[]; unscaled: number[] }[];
}

export interface ConformanceManifest {
  schema: number;
  generator: {
    script: string;
    sha256: string;
    command: string;
    python: string;
    nibabel: string;
    numpy: string;
  };
  cases: ConformanceCase[];
}

export const manifest: ConformanceManifest = JSON.parse(
  readFileSync(join(FIXTURE_ROOT, 'manifest.json'), 'utf8')
);

export function fixturePath(c: ConformanceCase): string {
  return join(FIXTURE_ROOT, c.file);
}

/** Fresh, exactly-sized ArrayBuffer holding the fixture's on-disk bytes. */
export function fixtureBytes(c: ConformanceCase): ArrayBuffer {
  const data = readFileSync(fixturePath(c));
  return data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength) as ArrayBuffer;
}

/**
 * Tolerances (documented in tests/conformance/README.md).
 *
 * - Integer and unscaled float data: exact. Stored values are representable
 *   in the decoded TypedArray and in the manifest's float64 JSON.
 * - Scaled data decoded into Float32 (readVol, readVec): 1e-6 relative to
 *   max(1, |expected|) — about 8 float32 ulps.
 * - Scaled data decoded into Float64 (readNiftiArrayBuffer): 1e-12 relative.
 * - Affines / world coordinates: 1e-6 relative to max(1, |expected|). Header
 *   transforms are stored as float32 (NIfTI-1); both libraries evaluate the
 *   same float32 parameters in double precision, so real differences are
 *   orders of magnitude larger than this.
 */
export const TOL = {
  float32Scaled: 1e-6,
  float64Scaled: 1e-12,
  geometry: 1e-6,
} as const;

function scaledDiff(actual: number, expected: number): number {
  return Math.abs(actual - expected) / Math.max(1, Math.abs(expected));
}

/** Assert two numeric sequences agree within a relative tolerance (0 = exact). */
export function expectClose(
  actual: ArrayLike<number>,
  expected: ArrayLike<number>,
  tol: number,
  label: string
): void {
  expect(actual.length, `${label}: length`).toBe(expected.length);
  let worst = -1;
  let worstErr = 0;
  for (let i = 0; i < expected.length; i++) {
    const a = Number(actual[i]);
    const e = Number(expected[i]);
    const err = tol === 0 ? (Object.is(a, e) || a === e ? 0 : Infinity) : scaledDiff(a, e);
    if (!(err <= tol) && (worst < 0 || err > worstErr)) {
      worst = i;
      worstErr = err;
    }
  }
  if (worst >= 0) {
    expect.fail(
      `${label}: element ${worst} = ${Number(actual[worst])}, expected ${Number(expected[worst])} ` +
        `(scaled error ${worstErr}, tolerance ${tol})`
    );
  }
}

export function expectMatrixClose(actual: number[][], expected: Matrix4, label: string): void {
  expect(actual.length, `${label}: rows`).toBe(4);
  expectClose(actual.flat(), expected.flat(), TOL.geometry, label);
}

/** nibabel axcode for a neuroimjs NamedAxis (neuroim names the axis by its origin side). */
const AXCODE: Record<string, string> = {
  LEFT_RIGHT: 'R',
  RIGHT_LEFT: 'L',
  POST_ANT: 'A',
  ANT_POST: 'P',
  INF_SUP: 'S',
  SUP_INF: 'I',
};

export function axcodes(axes: readonly NamedAxis[]): string[] {
  return axes.map(axis => AXCODE[axis.name] ?? `?${axis.name}`);
}

/**
 * Known neuroimjs/nibabel discrepancies, keyed by case id then check name.
 * Each entry turns the corresponding test into `it.fails`, so the suite stays
 * green while the bug exists and goes red (prompting removal of the entry)
 * once it is fixed. NEVER loosen a tolerance instead of adding an entry here.
 */
export type KnownDiscrepancies = Record<string, Record<string, string>>;

export function conformanceIt(
  known: KnownDiscrepancies,
  caseId: string,
  check: string,
  fn: () => unknown | Promise<unknown>
): void {
  const reason = known[caseId]?.[check] ?? known['*']?.[check];
  if (reason) {
    it.fails(`${check} [known discrepancy: ${reason}]`, fn);
  } else {
    it(check, fn);
  }
}
